class Prime{
	static String top10Movies[] = {"The idea of you","The big sick","American Fiction","Manchester by the Sea","The report","Saltburn","12 Angry men","Small axe","Air","I want you back","Nanny"};
	static String englishMovies[] = {"Road house","Thirteen lives","Upgraded","The lost city of Z","The outfit","Infinite","Super 8","The northman","The tomorrow war","A beautiful mind","Nobody","The getlemen","7500","John wick","Panic room","The report","The safe house","Inception","Imaginary","Dunkirk","Beast","The town","Get out","Locke","Musica","Upgraded","Chemical Hearts"};
	static String kannadaMovies[] = {"For regn","Yuva","Case of kondana","Sapta sagaradaache ello","Kantara","Tatsama Tadbhava","Love mocktail","Dia","Rathnan prapancha","Avatara purusha","Avane srimannarayana","Roberrt","Madhagaja","Katheyondu shuruvagide","Gantumoote","Kotogobba 3","Triple riding","Sugar factory","99","Bharaate","Love birds","Family pack","Old monk","Ninna sanihake","Orange","Jessie","Law","Kousalya supraja rama","Tagaru palya"};
	static String hindhiMovies[] = {"Raazi","War","Thappad","Rocky aur rani","Ghazi","V","Section 375","Jalsa","Joram","Batla House","Operation valentine","Yodha","Ghazi","Dybbuk","Pari","Pathaan","Sherni","Businessman","Vada chennai","Satya","Tiger 3","Kesari","Toofan","Lakshya","Captain Miller","Bell bottom","Custody","Bholaa","Haider","Maharshi"};
	static String koreanSeries[] = {"May I help you?","Island","Tale of the nine tailed","Heartbeat","Marry my husband","Death's game","My man is cupid","Taxi driver","The penthouse","W","Your honor","Cheer up","Oh my ghost","My dearest","Numbers","The good doctor","Familiar wife","Come and hug me","My first love","Tempted","Another miss oh","apartment 404","Beyond evil","Money flower","Payback","The killing vote","The one and only"};
public static void main(String[] movies){
System.out.println("THE TOP 10 MOVIES ARE :" +top10Movies[0]+"\n"+top10Movies[1]+ "\n"+top10Movies[2]+"\n"+top10Movies[3]+"\n"+top10Movies[4]+"\n"+top10Movies[5]+"\n"+top10Movies[6]+"\n"+top10Movies[7]+"\n"+top10Movies[8]+"\n"+top10Movies[9]+ "\n"+top10Movies[10]);
System.out.println("\n");
System.out.println("\n");
System.out.println("THE ENGLISH MOVIES ARE :" +englishMovies[0]+"\n"+englishMovies[1]+"\n"+englishMovies[2]+"\n"+englishMovies[3]+"\n"+englishMovies[4]+"\n"+englishMovies[5]+"\n"+englishMovies[6]+"\n"+englishMovies[7]+"\n"+englishMovies[8]+"\n"+englishMovies[9]+"\n"+englishMovies[10]+"\n"+englishMovies[11]+"\n"+englishMovies[12]+"\n"+englishMovies[13]+"\n"+englishMovies[14]+"\n"+englishMovies[15]+"\n"+englishMovies[16]+"\n"+englishMovies[17]+"\n"+englishMovies[18]+"\n"+englishMovies[19]+"\n"+englishMovies[20]+"\n"+englishMovies[21]+"\n"+englishMovies[22]+"\n"+englishMovies[23]+"\n"+englishMovies[24]+"\n"+englishMovies[25]+"\n"+englishMovies[26]);
System.out.println("\n");
System.out.println("\n");
System.out.println("THE KANNADA MOVIES ARE :" +kannadaMovies[0]+"\n"+kannadaMovies[1]+"\n"+kannadaMovies[2]+"\n"+kannadaMovies[3]+"\n"+kannadaMovies[4]+"\n"+kannadaMovies[5]+"\n"+kannadaMovies[6]+"\n"+kannadaMovies[7]+"\n"+kannadaMovies[8]+"\n"+kannadaMovies[9]+"\n"+kannadaMovies[10]+"\n"+kannadaMovies[11]+"\n"+kannadaMovies[12]+"\n"+kannadaMovies[13]+"\n"+kannadaMovies[14]+"\n"+kannadaMovies[15]+"\n"+kannadaMovies[16]+"\n"+kannadaMovies[17]+"\n"+kannadaMovies[18]+"\n"+kannadaMovies[19]+"\n"+kannadaMovies[20]+"\n"+kannadaMovies[21]+"\n"+kannadaMovies[22]+"\n"+kannadaMovies[23]+"\n"+kannadaMovies[24]+"\n"+kannadaMovies[25]+"\n"+kannadaMovies[26]+"/n"+kannadaMovies[27]+"\n"+kannadaMovies[28]);
System.out.println("\n");
System.out.println("\n");
System.out.println("THE HINDHI KANNADA MOVIES ARE :" +hindhiMovies[0]+"\n"+hindhiMovies[1]+"\n"+hindhiMovies[2]+"\n"+hindhiMovies[3]+"\n"+hindhiMovies[4]+"\n"+hindhiMovies[5]+"\n"+hindhiMovies[6]+"\n"+hindhiMovies[7]+"\n"+hindhiMovies[8]+"\n"+hindhiMovies[9]+"\n"+hindhiMovies[10]+"\n"+hindhiMovies[11]+"\n"+hindhiMovies[12]+"\n"+hindhiMovies[13]+"\n"+hindhiMovies[14]+"\n"+hindhiMovies[15]+"\n"+hindhiMovies[16]+"\n"+hindhiMovies[17]+"\n"+hindhiMovies[18]+"\n"+hindhiMovies[19]+"\n"+hindhiMovies[20]+"\n"+hindhiMovies[21]+"\n"+hindhiMovies[22]+"\n"+hindhiMovies[23]+"\n"+hindhiMovies[24]+"\n"+hindhiMovies[25]+"\n"+hindhiMovies[26]+"\n"+hindhiMovies[27]+"\n"+hindhiMovies[28]+"/n"+hindhiMovies[29]);
System.out.println("\n");
System.out.println("\n");
System.out.println("THE KOREAN SERIES ARE : " +koreanSeries[0]+"\n"+koreanSeries[1]+"\n"+koreanSeries[2]+"\n"+koreanSeries[3]+"\n"+koreanSeries[4]+"\n"+koreanSeries[5]+"\n"+koreanSeries[6]+"\n"+koreanSeries[7]+"\n"+koreanSeries[8]+"\n"+koreanSeries[9]+"\n"+koreanSeries[10]+"\n"+koreanSeries[11]+"\n"+koreanSeries[12]+"\n"+koreanSeries[13]+"\n"+koreanSeries[14]+"\n"+koreanSeries[15]+"\n"+koreanSeries[16]+"\n"+koreanSeries[17]+"\n"+koreanSeries[18]+"\n"+koreanSeries[19]+"\n"+koreanSeries[20]+"\n"+koreanSeries[21]+"\n"+koreanSeries[22]+"\n"+koreanSeries[23]+"\n"+koreanSeries[24]+"\n"+koreanSeries[25]+"\n"+koreanSeries[26]);
}
}